apiVersion: v2
name: cluster-autoscaler
description: Cluster Autoscaler chart

type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: cluster-autoscaler
    version: 9.28.0
    repository: https://kubernetes.github.io/autoscaler