node-local-dns:
  # Add any values needed for Node Local DNS here
  logLevel: 2
  dnsDomain: cluster.local
  dnsServer: kube-dns.kube-system.svc.cluster.local
  forwardTarget: 8.8.8.8
  nodeSelector:
    kubernetes.io/os: linux
  tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Exists"
  service:
    type: ClusterIP